[package]
name = "seahorse-compile"
version = "0.1.5" # mirror seahorse-lang version
edition = "2021"
description = "Seahorse compiler for Solana Playground with WASM."
repository = "https://github.com/solana-playground/solana-playground"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
seahorse-lang = "0.1.5"
console_error_panic_hook = "0.1.7"
solana-playground-utils-wasm = { path = "../utils/solana-playground-utils" }
wasm-bindgen = "0.2.81"
